### ISSUE TITLE
Lookless tiles should work with slackbot

### ISSUE THREAD

**Issue by RichardCzechowski** [looker/lookerbot#132] opened 2018-01-25 18:23 UTC
This one is from @maxcorbin:This is a variation on this theme of lookless dashboards not working everywhere.Basically Slackbot can't query a Lookless dashboard, but there is no indication that this won't work from the customer's perspective.

**Comment by lameyer** [comment] 2018-01-25 18:30
Dupe of https://github.com/looker/lookerbot/issues/131, which I believe is fixed and the person just needs to update

**Closed by lameyer** 2018-01-25 18:30 UTC
