### ISSUE TITLE
What address to use to schedule jobs to slack

### ISSUE THREAD

**Issue by jedgecombe** [looker/lookerbot#122] opened 2017-10-07 10:07 UTC
Love the bot! Really cool and should be so useful. I've followed your readme and have the bot setup and I can query it inside slack but I'm struggling to setup scheduled jobs and I think its because I have the address wrong. It's hosted on heroku. This is the address I've tried (just interchanging the capital letters).

https://MY-HEROKU-APP-NAME.herokuapp.com/slack/post/channel/MY-CHANNEL-NAME

where MY-HEROKU-APP-NAME is the unique name of the heroku app I've made and MY-CHANNEL-NAME is the name of the slack channel.

The lookerbot is added to the channel and I have 'activated incoming webhooks' for this slack channel. I can query the lookerbot successfully from within the channel but I want to setup the scheduled jobs to post regularly. Any help would be hugely appreciated!

This is the error that I get emailed to me from Looker, again I've substituted private information.

```
The scheduled job "LOOK NAME"[111111] failed for https://MY-HEROKU-APP-NAME.herokuapp.com/slack/post/channel/MY-CHANNEL-NAME. Please visit your content to view and resolve the error, or contact your Looker administrator if you need further assistance.

Error: Could not send webhook to "https://MY-HEROKU-APP-NAME.herokuapp.com/slack/post/channel/MY-CHANNEL-NAME". <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>Payload Too Large</pre> </body> </html> (Webhook ID: XXXXXXXX)
```

**Comment by jedgecombe** [comment] 2017-10-09 11:27
the problem was not my url but that I was trying to schedule a dashboard, rather than a look. Big thanks to Bernard from looker who helped me out!

**Comment by wilg** [comment] 2017-10-09 16:30
Ah, yes, dashboards aren't supported. I think this makes it a duplicate of https://github.com/looker/lookerbot/issues/58, but obviously the error here is pretty cryptic.

**Closed by wilg** 2017-10-09 16:30 UTC
